using keyctl now to save bw session key

diff --git a/bin/git-credential-bw b/bin/git-credential-bw
--- a/bin/git-credential-bw
+++ b/bin/git-credential-bw
@@ -4,48 +4,105 @@
 #
 #
 
+# what section to store options in the git config
+declare -r  section="credential.bw"
+
 trap 'exit 1' SIGINT
 help(){
 	echo "
 Bitwarden Git Credential Helper
 
 Usage:
-  git-credential-bw get
+  git-credential-bw <command>
   git-credential-bw [-h|--help]
 
 Options:
-  -h --help     Show this screen."
+  -h --help     Show this screen.
+
+Command:
+  get  - get the credentials username and password.
+  set  - set required options.
+    itemSearchString - string to search bitwarden for and must find only one item.
+    maxAttempts      - Max number of times to prompt the user before failing.
+                       -1 makes this limit infinite..
+    bw               - bitwarden cli command to use.
+    custom-field     - custom field to use instead of password
+    sessionFilePath  - Path to temporarily store the bitwarden session key.
+                       Recommended to put in a temp folder.
+                       Note that this session key can be invalidated at any moment by running 'bw lock'.
+                       if unset, use keyctl instead.
+
+Current Options:
+  itemSearchString - $(get_git_config "itemSearchString")
+  maxAttempts      - $(get_git_config "maxAttempts")
+  bw               - $(get_git_config "bw")
+  custom-field     - $(get_git_config "custom-field")
+  sessionFilePath  - $(get_git_config "sessionFilePath")
+" >&2
 }
-get(){
+
+get_git_config()
+{
+    local data=""
+
+    if [ -n "$1" ]
+    then
+        data="$(git config "${section}.${1}")"
+        if [ -z "$data" -a -n "$2" ]
+        then
+            git config --global ${section}.${1} "$2" && data="$2"
+        fi
+    fi
+
+    echo "$data"
+}
+
+config_check()
+{
+    if [ -n "$1" -a -z "$2" ]
+    then
+        echo "
+error: no value for ${section}.${1}. Please set a \"value\" as follows
+git config ${section}.${1} \"value\"
+git config --global ${section}.${1} \"value\"
+" >&2
+        exit 1
+    fi
+}
+
+get()
+{
 	# You can configure these settings
 
 	#Path to temporarily store the bitwarden session key.
 	#Recommended to put in a temp folder.
 	#Note that this session key can be invalidated at any moment by running 'bw lock'
-    if [ -d /run/user/1000 ]
-    then
-        declare -r sessionFilePath="/run/user/1000/git-credential-bw.key"
-    else
-	    declare -r sessionFilePath="/tmp/git-credential-bw.key"
-    fi
+    declare -r sessionFilePath="$(get_git_config "sessionFilePath" "")"
+    #if [ -d /run/user/1000 ]
+    #then
+    #    declare -r sessionFilePath="/run/user/1000/git-credential-bw.key"
+    #else
+	#    declare -r sessionFilePath="/tmp/git-credential-bw.key"
+    #fi
 
 	#String to give to bw to search the correct item
-	declare -r itemSearchString="github.com"
+	#declare -r itemSearchString="github.com"
+    declare -r itemSearchString="$(get_git_config "itemSearchString")"
+    config_check "itemSearchString" "$itemSearchString"
 
 	#Max number of times to prompt the user before failing.
 	#-1 makes this limit infinite
-	declare -r maxAttempts=3
+	#declare -r maxAttempts=3
+    declare -r maxAttempts="$(get_git_config "maxAttempts" 3)"
+    config_check "maxAttempts" "$maxAttempts"
 
-    if [ -x /usr/local/bin/bw ]
-    then
-        declare -r bw="/usr/local/bin/bw"
+    # the bitwarded cli program to use
+    declare -r bw="$(get_git_config "bw" bw)"
 
-    elif [ -x /usr/bin/bw ]
-    then
-        declare -r bw="/usr/bin/bw"
-    else
-        declare -r bw="bw"
-    fi
+    # what custom field the password is in. If not set, use password field instead
+    declare -r custom_field="$(get_git_config "custom-field")"
+
+    # check if we have 
 
 	logInStatus(){
 		declare bwReturn="$($bw status)"
@@ -54,10 +111,28 @@ get(){
 		echo $statusString
 	}
 
-	if [ ! -f "$sessionFilePath" ]; then
-		touch "$sessionFilePath"
+    # read saved key
+	if [ -n "$sessionFilePath" ]
+    then
+        if [ ! -f "$sessionFilePath" ]
+        then
+		    touch "$sessionFilePath"
+        fi
+	    export BW_SESSION="$(cat "$sessionFilePath")"
+    else
+        if ! which -s keyctl
+        then
+            error "
+keyctl: command not found. Either install it or set sessionFilePath
+to store session key to a file, as follows:
+git config ${section}.sessionFilePath \"value\"
+git config --global ${section}.sessionFilePath \"value\"
+" >&2
+        else
+            export BW_SESSION="$( id=$(keyctl request user "BW_SESSION" @u 2>/dev/null) \
+                && keyctl print "$id")"
+        fi
 	fi
-	export BW_SESSION="$(cat "$sessionFilePath")"
 
 	declare attemptNum=0
 	declare currStatus="$(logInStatus)"
@@ -86,7 +161,13 @@ get(){
 	fi
 
 	$bw sync > /dev/null
-	echo "$BW_SESSION" > "$sessionFilePath"
+    # save key
+	if [ -n "$sessionFilePath" ]
+    then
+	    echo "$BW_SESSION" > "$sessionFilePath"
+    else
+        echo -n "$BW_SESSION" | keyctl padd user "BW_SESSION" @u > /dev/null
+    fi
 
 	if [ "$1" == "raw" ]; then
 		echo "$BW_SESSION"
@@ -95,14 +176,43 @@ get(){
 		declare loginOut="$(echo $item | jq .login)"
 		declare username="$(echo $loginOut | jq -r .username)"
 		declare password="$(echo $loginOut | jq -r .password)"
-        declare fine_grained_key="$(echo $item | jq -r '.fields[] | select(.name=="fine grained token")')"
-        declare fine_grained_key="$(echo $fine_grained_key | jq -r .value )"
-        [ -n "$fine_grained_key" ] && password="$fine_grained_key"
+        if [ -n "$custom_field" ]
+        then
+            #declare fine_grained_key="$(echo $item | jq -r '.fields[] | select(.name=="fine grained token")')"
+            declare fine_grained_key="$(echo $item | jq -r ".fields[] | select(.name==\"$custom_field\")")"
+            declare fine_grained_key="$(echo $fine_grained_key | jq -r .value )"
+            [ -n "$fine_grained_key" ] && password="$fine_grained_key"
+        fi
 		echo "username=$username"
 		echo "password=$password"
 	fi
 }
 
+set()
+{
+    if [ -n "$1" -a -n "$2" ]
+    then
+        git config --global "credential.bw.$1" "$2"
+    else
+        help
+        echo "please provive an option and a value to set it to." >&2
+    fi
+}
+
+init()
+{
+    git config --global credential.helper bw \
+        && echo "git-credential-bw is now set to be the credential manager." >&2 \
+        && echo "Please set required options now." >&2
+    help
+}
+
+error()
+{
+    echo "$@" >&2
+    help
+    exit 1
+}
 
 if [ "$#" -eq 0 ]; then
 	help;
@@ -111,43 +221,47 @@ else
 	declare isRaw=false
 	declare isHelp=false
 	declare command
-	while [ $# -gt 0 ]; do
+	while [ $# -gt 0 -a -z "$command" ]; do
 		case "$1" in
 			-h|--help)
 				isHelp=true
-				exit
+				break
 				;;
 			-r|--raw)
 				isRaw=true
 				;;
-			*)
-				if [ -z "$(echo "$1" | grep -o "-")" ]; then
-					if [ -z "$command" ]; then
-						command="$1"
-					else
-						echo "Unknown Argument $1" >&2
-						exit 1
-					fi
-				else
-					echo "Unknown Argument $1" >&2
-					exit 1
-				fi
+			-*)
+                error "$1: Unknown option"
+                ;;
+            *)
+                command="$1"
 				;;
 		esac
 		shift
 	done
 	if $isHelp; then
 		help
-		exit
 	elif [ -n "$command" ]; then
 		case "$command" in
 			get)
 				get
 				exit $?
 				;;
+            init)
+                init
+                exit $?
+                ;;
+            set)
+                set "$@"
+                exit $?
+                ;;
 			*)
-				exit 1
+                error "$command: unknown command"
+                ;;
 		esac
+    else
+        help
+        exit
 	fi
 fi
 
diff --git a/sbin/bw b/sbin/bw
--- a/sbin/bw
+++ b/sbin/bw
@@ -20,6 +20,7 @@ main()
     wget="/usr/bin/wget"
     unzip="/usr/bin/unzip"
     dirname="/usr/bin/dirname"
+    keyctl="/usr/bin/keyctl"
     command=""
     opt=""
 
@@ -90,6 +91,7 @@ do_init()
     [ -x "$wget" ]     || err "Unable for find wget program"
     [ -x "$unzip" ]    || err "Unable for find unzip program"
     [ -x "$dirname" ]  || err "Unable for find dirname program"
+    [ -x "$keyctl" ]   || err "Unable for find dirname keyctl"
     info "do init stuff done"
 }
 
@@ -199,7 +201,8 @@ bw_unlock()
                     unset BW_PASSWORD
                     export BW_SESSION
                     info got BW_SESSION=$BW_SESSION
-                    echo "$BW_SESSION" > "${tmp}/${bw_session_f}"
+                    #echo "$BW_SESSION" > "${tmp}/${bw_session_f}"
+                    echo -n "$BW_SESSION" | "$keyctl" padd user "BW_SESSION" @u > /dev/null
                     break
                 else
                     unset BW_PASSWORD
@@ -234,29 +237,21 @@ check_and_unlock()
     if "$bw" unlock --check > /dev/null 2>&1
     then
         info "bw is unlocked."
-        [ -n "$BW_SESSION" ] && echo -n "$BW_SESSION" > "${tmp}/${bw_session_f}"
+        #[ -n "$BW_SESSION" ] && echo -n "$BW_SESSION" > "${tmp}/${bw_session_f}"
+        [ -n "$BW_SESSION" ] && echo -n "$BW_SESSION" | "$keyctl" padd user "BW_SESSION" @u > /dev/null
 
-    elif tmp_is_tmpfs
-    then
-        info "yes tmp is a tmpfs."
-        if [ -e "${tmp}/${bw_session_f}" ]
+    else
+        info "try to use saved session key."
+        export BW_SESSION="$( id=$(keyctl request user "BW_SESSION" @u 2>/dev/null) \
+            && keyctl print "$id")"
+
+        if "$bw" unlock --check > /dev/null 2>&1
         then
-            info "${tmp}/${bw_session_f}: try to use this session key."
-            export BW_SESSION="$(<${tmp}/${bw_session_f})"
-            if "$bw" unlock --check > /dev/null 2>&1
-            then
-                info "unlocked by ${tmp}/${bw_session_f}."
-            else
-                info "unlock by ${tmp}/${bw_session_f} failed."
-                "$rm" -f "${tmp}/${bw_session_f}"
-                [ "$check" == "--check" ] || bw_unlock
-            fi
+            info "unlocked by aved key"
         else
-            info "${tmp}/${bw_session_f}: no saved session key found."
+            info "unlock by saved key failed."
             [ "$check" == "--check" ] || bw_unlock
         fi
-    else
-        err "${tmp}: not a mounted tmpfs."
     fi
 }
 
