more fixes

diff --git a/bin/git-checkbin b/bin/git-checkbin
--- a/bin/git-checkbin
+++ b/bin/git-checkbin
@@ -25,6 +25,36 @@ sha256sum()
 	done
 }
 
+hook_add()
+{
+	local hook="$1"
+	local line="$2"
+
+	# need to escape \\ and [ and ] in the regex pattern
+	# but still need to write the original line only
+	regex="${line//\\/\\\\}"
+	regex="${regex//[/\\[}"
+	regex="${regex//]/\\]}"
+
+	[ $# == 2 ] || return 1
+
+	if [ ! -d "$GIT_DIR/hooks" ]
+	then
+		echo "Error: unable to find hooks directory $GIT_DIR/hooks"
+		return 1
+	fi
+
+	[ -e "$GIT_DIR/hooks/${hook}" ] || echo "#!/bin/bash" > "$GIT_DIR/hooks/${hook}"
+
+	if [  "$(/bin/grep --count "^${regex}\$" "$GIT_DIR/hooks/${hook}")" == 0 ]
+	then
+		echo "${line}" >> "$GIT_DIR/hooks/${hook}"
+		echo "hook ${hook} updated." 
+	fi
+
+	/bin/chmod 755 "$GIT_DIR/hooks/${hook}"
+}
+
 #
 # process command line options
 #
@@ -34,43 +64,11 @@ do
 done
 
 case "$1" in
+	"enable")	echo "$filter enabled";  /usr/bin/git config hooks.${filter} true;;
+	"disable")	echo "$filter disabled"; /usr/bin/git config hooks.${filter} false;;
 	"init")
-		if [ -z "$GIT_DIR" ]
-		then 
-			echo "Error: unable to find git hooks folder."
-			echo "       Please add \"/usr/bin/git ${filter}\" to pre-commit hook manualy."
-			exit 1
-		fi
-
-		if [ -e "$GIT_DIR/hooks/pre-commit" -a \
-		     "$(/bin/grep --count "^/usr/bin/git ${filter}$" "$GIT_DIR/hooks/pre-commit")" == 0 \
-		   ]
-		then
-			echo "Error: \"$GIT_DIR/hooks/pre-commit\" already exists."
-			echo "       Please add \"/usr/bin/git ${filter}\" to pre-commit hook manualy."
-			exit 1
-		else
-			echo "Adding ${filter} to \"$GIT_DIR/hooks/pre-commit\""
-			echo "#!/bin/bash" > "$GIT_DIR/hooks/pre-commit"
-			echo "/usr/bin/git ${filter}" >> "$GIT_DIR/hooks/pre-commit"
-			echo "git ${filter} is now active."
-		fi
-		/bin/chmod 755 "$GIT_DIR/hooks/pre-commit"
-
-		pre_push="0"
-		if [ ! -e "$GIT_DIR/hooks/pre-commit" ]
-		then
-			echo "#!/bin/bash" > "$GIT_DIR/hooks/pre-push"
-		else
-			pre_push="$(/usr/bin/tail "$GIT_DIR/hooks/pre-push" | /bin/grep --count "^exit 1$")"
-		fi
-
-		if [ "$pre_push" == 0 ]
-		then
-			echo "push disabled in \"$GIT_DIR/hooks/pre-push\""
-			echo "exit 1" >> "$GIT_DIR/hooks/pre-push"
-		fi
-		/bin/chmod 755 "$GIT_DIR/hooks/pre-push"
+		hook_add pre-commit "/usr/bin/git ${filter}"
+		hook_add post-merge "[ \"\$(/usr/bin/git config --get hooks.${filter})\" == true ] && echo \"pull disabled in \\\"$GIT_DIR/hooks/post-merge\\\"\" && exit 1"
 
 		/usr/bin/git config filter.${filter}.clean "git-${filter} clean -- %f"
 		/usr/bin/git config filter.${filter}.smudge "git-${filter} smudge -- %f"
