removed git-lfs stracked files

diff --git a/sbin/bw b/sbin/bw
--- a/sbin/bw
+++ b/sbin/bw
@@ -5,7 +5,8 @@ main()
     #DEBUG="1"
     log="/tmp/bw.log"
 
-    bw="/usr/local/scripts/bin/bw"
+    bw="/usr/local/bin/bw"
+    bw_download_link="https://vault.bitwarden.com/download/?app=cli&platform=linux"
     tmp="$( /usr/bin/readlink -f "$HOME/.ssh/tmp" )"
     xhost="/usr/bin/xhost"
     tty="$(/usr/bin/tty)"
@@ -14,12 +15,20 @@ main()
     fgrep="/usr/bin/fgrep"
     grep="/usr/bin/grep"
     printf="/usr/bin/printf"
+    wget="/usr/bin/wget"
+    unzip="/usr/bin/unzip"
     command=""
     opt=""
 
     pinentry="$(get_pinentry)"
 
     do_init
+
+    if [ ! -x "$bw" ]
+    then
+       "$wget" --continue -O "/tmp/bw.zip" "$bw_download_link" 
+       "$unzip" -d "$(/usr/bin/dirname "$bw")" "/tmp/bw.zip" bw
+    fi
 
     if [ -x "$bw" ]
     then
@@ -67,14 +76,16 @@ do_init()
     export PATH="/usr/local/scripts/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
 
     [ -x "$pinentry" ] || err "Unable for find pinentry program"
-    [ -x "$xhost" ] || err "Unable for find xhost program"
+    [ -x "$xhost" ]  || err "Unable for find xhost program"
     info "xhost = $xhost"
-    [ -n "$tty" ] || err "Unable for find tty"
-    [ -x "$rm" ] || err "Unable for find rm program"
-    [ -x "$mount" ] || err "Unable for find mount program"
-    [ -x "$grep" ] || err "Unable for find grep program"
-    [ -x "$fgrep" ] || err "Unable for find fgrep program"
+    [ -n "$tty" ]    || err "Unable for find tty"
+    [ -x "$rm" ]     || err "Unable for find rm program"
+    [ -x "$mount" ]  || err "Unable for find mount program"
+    [ -x "$grep" ]   || err "Unable for find grep program"
+    [ -x "$fgrep" ]  || err "Unable for find fgrep program"
     [ -x "$printf" ] || err "Unable for find printf program"
+    [ -x "$wget" ]   || err "Unable for find wget program"
+    [ -x "$unzip" ]  || err "Unable for find unzip program"
     info "do init stuff done"
 }
 
